sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/shuup/build_resources"
env:
  - TOXENV=sanity
  #- TOXENV=flake8
  - TOXENV=isort
  #- TOXENV=license_headers
matrix:
  include:
    #- {python: 2.7, env: TOXENV=py27-django18-nomigrations}
    #- {python: 3.4, env: TOXENV=py34-django18-nomigrations}
    #- {python: 3.5, env: TOXENV=py35-django18-nomigrations}
    - {python: 2.7, env: TOXENV=py27-django19-nomigrations}
    - {python: 3.4, env: TOXENV=py34-django19-nomigrations}
    #- {python: 3.5, env: TOXENV=py35-django19-nomigrations}
    # Browser tests are disabled, since they cause false errors
    # - {python: 3.5, env: TOXENV=py35-nomigrations-nocoverage-browser}
install:
  - pip install -U pip setuptools
  - pip install tox
  #- pip install coveralls
  - pip install codecov
#before_install:
  #- "nvm install 4"
  #- "nvm use 4"
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- "npm install -g selenium-standalone@4.5.3"
  #- "selenium-standalone install"
  #- "selenium-standalone start &"
script:
  - tox
after_success:
  #- coveralls
  - codecov
